import { Category, CampusLocation, Department, YearOfStudy, LostFoundItem } from './types';

export const RTC_LOCATIONS: CampusLocation[] = [
  'Main/Admin Block',
  'CSE / Computer Science area',
  'IT area',
  'ECE area',
  'Mechanical area',
  'Biomedical area',
  'AI & Data Science area',
  'Library',
  'Computer Labs',
  'Engineering Labs',
  'Auditorium',
  'Food Court / Canteen',
  'Hostel',
  'Girls Hostel',
  'Boys Hostel',
  'Sports Ground',
  'Basketball Court',
  'Volleyball Court',
  'Parking Area',
  'Entrance / Gate',
  'Transport Area',
  'Skill Centre',
  'RAISE / Innovation Centre',
  'Other',
];

export const RTC_CAMPUS_LOCATIONS = RTC_LOCATIONS;

export const RTC_DEPARTMENTS: Department[] = [
  'CSE',
  'CSE (AI & ML)',
  'CSE (Cyber Security)',
  'AI & Data Science',
  'IT',
  'ECE',
  'Biomedical Engineering',
  'Mechanical Engineering',
  'Agricultural Engineering',
  'Biotechnology',
  'Other',
];

export const RTC_YEARS: YearOfStudy[] = [
  '1st Year',
  '2nd Year',
  '3rd Year',
  '4th Year',
  'Faculty / Staff',
];

export const CATEGORIES: Category[] = [
  'Electronics',
  'Calculators & Lab Gear',
  'ID & Cards',
  'Keys',
  'Bags & Backpacks',
  'Clothing',
  'Books & Stationery',
  'Watches & Jewellery',
  'Accessories',
  'Other',
];

export const RTC_DEMO_ITEMS: LostFoundItem[] = [
  {
    id: 'RTC-DEMO-01',
    type: 'lost',
    title: 'Black Leather RFID Wallet',
    category: 'Accessories',
    location: 'Library',
    locationDetail: '2nd Floor Reference Section, Desk #18 near Digital Library',
    date: '2026-08-30',
    time: '02:30 PM',
    description: 'Black bi-fold leather wallet with red contrast stitching. Contains college transit pass and bank card.',
    distinctiveDetails: 'Contains an old Rathinam Techzone entrance token in the coin sleeve and a passport-size photo inside the ID window.',
    reward: '₹500 / Sincere Gratitude',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    status: 'open',
    userId: 'demo-user-1',
    userName: 'Karthik Raja',
    userEmail: 'karthik.r@rathinam.in',
    userDept: 'CSE',
    isDemo: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 28,
    tags: ['Wallet', 'Library', 'Leather', 'RFID'],
  },
  {
    id: 'RTC-DEMO-02',
    type: 'found',
    title: 'Rathinam College Student ID Card',
    category: 'ID & Cards',
    location: 'CSE / Computer Science area',
    locationDetail: 'Ground Floor corridor near CSE Lab 2 notice board',
    date: '2026-08-31',
    time: '11:15 AM',
    description: 'RTC Student ID Card attached to a blue Rathinam lanyard with RFID card protector.',
    keptAt: 'CSE Department HOD Staff Room with Lab Assistant',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    status: 'open',
    userId: 'demo-user-2',
    userName: 'Prof. Anitha S.',
    userEmail: 'anitha.cse@rathinam.in',
    userDept: 'CSE',
    isDemo: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    tags: ['Student ID', 'CSE Area', 'Lanyard', 'RFID'],
  },
  {
    id: 'RTC-DEMO-03',
    type: 'lost',
    title: 'Casio fx-991EX Scientific Calculator',
    category: 'Calculators & Lab Gear',
    location: 'Engineering Labs',
    locationDetail: 'Mechanical Workshop / CAD Lab workstation #12',
    date: '2026-08-29',
    time: '04:10 PM',
    description: 'Black and white ClassWiz scientific calculator used during afternoon CAD practicals.',
    distinctiveDetails: 'Has a silver "RTC CAD 2026" label taped inside the sliding back cover and a small yellow smiley sticker on the solar panel corner.',
    reward: 'Treat at Food Court',
    imageUrl: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=800&auto=format&fit=crop&q=80',
    status: 'open',
    userId: 'demo-user-3',
    userName: 'Vignesh P.',
    userEmail: 'vignesh.mech@rathinam.in',
    userDept: 'Mechanical Engineering',
    isDemo: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 48,
    tags: ['Casio', 'Calculator', 'Engineering Lab', 'ClassWiz'],
  },
  {
    id: 'RTC-DEMO-04',
    type: 'found',
    title: 'Matte Black Wireless Earbuds in Charging Case',
    category: 'Electronics',
    location: 'Food Court / Canteen',
    locationDetail: 'Canteen outdoor seating table near the Nescafe counter',
    date: '2026-08-30',
    time: '01:45 PM',
    description: 'True wireless Bluetooth earbuds in a compact oval matte black charging case.',
    keptAt: 'Main Food Court Manager Cash Counter (Holding securely)',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    status: 'open',
    userId: 'demo-user-4',
    userName: 'Suresh Kumar',
    userEmail: 'suresh.fc@rathinam.in',
    userDept: 'Other',
    isDemo: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 22,
    tags: ['Earbuds', 'Food Court', 'Bluetooth', 'Matte Black'],
  },
  {
    id: 'RTC-DEMO-05',
    type: 'lost',
    title: 'Honda Bike Key with Marvel Keychain',
    category: 'Keys',
    location: 'Parking Area',
    locationDetail: 'Two-wheeler student parking bay near South Gate exit',
    date: '2026-08-31',
    time: '09:00 AM',
    description: 'Single Honda Activa key attached to a metal Captain America shield rotating keychain.',
    distinctiveDetails: 'A blue rubber ring around the key head with a small brass locker key attached.',
    reward: '₹200 Cash Reward',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&auto=format&fit=crop&q=80',
    status: 'open',
    userId: 'demo-user-5',
    userName: 'Divya M.',
    userEmail: 'divya.it@rathinam.in',
    userDept: 'IT',
    isDemo: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    tags: ['Keys', 'Parking Area', 'Honda', 'Keychain'],
  },
  {
    id: 'RTC-DEMO-06',
    type: 'found',
    title: 'Grey Lenovo ThinkPad Charger (65W Type-C)',
    category: 'Electronics',
    location: 'Computer Labs',
    locationDetail: 'IT Lab 1, Switch desk row B',
    date: '2026-08-30',
    time: '05:30 PM',
    description: 'Original Lenovo 65W USB-C fast charging power brick with velcro cable strap.',
    keptAt: 'IT Department Systems Lab In-Charge Desk',
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    status: 'open',
    userId: 'demo-user-6',
    userName: 'Lab Instructor Ramesh',
    userEmail: 'ramesh.lab@rathinam.in',
    userDept: 'IT',
    isDemo: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 18,
    tags: ['Lenovo', 'Charger', 'Computer Lab', 'Type-C'],
  },
];
